# Generated by Django 3.1.3 on 2020-11-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, max_length=32)),
                ('celular', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('t_created', models.DateField(auto_now_add=True)),
                ('t_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('t_created', models.DateField(auto_now_add=True)),
                ('t_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('t_created', models.DateField(auto_now_add=True)),
                ('t_modified', models.DateField(auto_now=True)),
                ('contatos', models.ManyToManyField(blank=True, to='checker.Pessoa')),
                ('pontos', models.ManyToManyField(blank=True, to='checker.Ponto')),
            ],
        ),
        migrations.AddField(
            model_name='ponto',
            name='visitas',
            field=models.ManyToManyField(blank=True, to='checker.Visita'),
        ),
    ]
