# Generated by Django 3.1.3 on 2020-11-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20201120_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
