# Generated by Django 3.1.3 on 2020-11-20 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_itembase_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='t_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='t_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
