# Generated by Django 3.1.3 on 2020-11-24 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checker', '0005_auto_20201120_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_arb', models.IntegerField(null=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='conformidade',
            field=models.CharField(choices=[('C', 'Conforme'), ('NC', 'Não Conforme'), ('NCR', 'Não Conforme Resolvida'), ('NA', 'Não Aplicável'), ('NO', 'Não Observado')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='itembase',
            name='id_arb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='avaliador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visita',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='plantao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visita',
            name='termino',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
