# Generated by Django 3.1.3 on 2020-11-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_auto_20201126_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponto',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rede',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visita',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
