# Generated by Django 3.1.3 on 2021-01-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_auto_20201214_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clientId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
