# Generated by Django 3.1.3 on 2021-01-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0014_item_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vCount',
            field=models.IntegerField(default=1),
        ),
    ]
