# Generated by Django 3.1.3 on 2021-01-29 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checker', '0015_profile_vcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rede',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='rede',
            name='contatos',
        ),
        migrations.AddField(
            model_name='rede',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
