# Generated by Django 3.1.3 on 2021-02-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0017_registertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('t_created', models.DateField(auto_now_add=True)),
                ('t_modified', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['t_created'],
            },
        ),
        migrations.RemoveField(
            model_name='itembase',
            name='in_trash',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='in_trash',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='in_trash',
        ),
        migrations.RemoveField(
            model_name='rede',
            name='in_trash',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='in_trash',
        ),
        migrations.AddField(
            model_name='itembase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rede',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inUse', models.BooleanField(default=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.checklist')),
                ('itemBase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker.itembase')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='itens',
            field=models.ManyToManyField(blank=True, through='checker.ChecklistItem', to='checker.ItemBase'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='rede',
            field=models.ManyToManyField(blank=True, to='checker.Rede'),
        ),
    ]
