# Generated by Django 3.1.3 on 2021-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0018_auto_20210211_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registertoken',
            name='rede',
        ),
        migrations.AddField(
            model_name='registertoken',
            name='redes',
            field=models.ManyToManyField(blank=True, to='checker.Rede'),
        ),
    ]
