# Generated by Django 3.1.3 on 2021-02-23 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checker', '0019_auto_20210212_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rede',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='redes', to=settings.AUTH_USER_MODEL),
        ),
    ]
