# Generated by Django 3.1.3 on 2021-02-23 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checker', '0020_auto_20210223_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rede',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='redes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='redes',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='checker.Rede'),
        ),
    ]
