# Generated by Django 3.1.3 on 2021-02-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0021_auto_20210223_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='assigned_to',
        ),
    ]
