# Generated by Django 3.1.3 on 2021-03-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0023_categoria_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembase',
            name='active',
        ),
    ]
